name: Workflow with automated approval

env:
  GH_TOKEN: ${{ github.token }}

concurrency: ci-${{ github.ref }}

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  
  push:
    branches: [ main ]

jobs:

  test:
    name: "Validate config"
    runs-on: ubuntu-20.04
    steps:
      - run: echo "test"
      
  manual-approval:
    name: "Waiting for automated approve of Deploymnent to ENV"
    environment: 'bot_prod'
    runs-on: ubuntu-20.04
    needs:
      - test
    steps:
      - run: echo "Approved to bot_prod"

  prod:
    name: 'Closed Workflow'
    runs-on: ubuntu-20.04
    needs: 
      - manual-approval
    steps:
      - run: echo "approved"

