name: Workflow with automated approval

env:
  GH_TOKEN: ${{ github.token }}

concurrency: ci-${{ github.ref }}

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:

  test:
    name: "Validate config"
    runs-on: ubuntu-20.04
    steps:
      - run: echo "test"
      
  automated-validation-approval:
    name: "Waiting for automated approve of Deploymnent to ENV"
    environment: 'bot_validation'
    runs-on: ubuntu-20.04
    needs:
      - test
    steps:
      - run: echo "Approved to bot_prod"

  transiton-to-deployment:
    name: 'End workflow2 '
    runs-on: ubuntu-20.04
    needs: 
      - automated-validation-approval
    steps:
      - name: Sleep for 2 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'


  automated-deployment-approval:
    name: 'Closed Workflow'
    environment: 'bot_deployment'
    runs-on: ubuntu-20.04
    needs: 
      - transiton-to-deployment
    steps:
      - run: echo "approved"

  transiton-to-completion:
    name: 'End workflow23'
    runs-on: ubuntu-20.04
    needs: 
      - automated-deployment-approval
    steps:
      - name: Sleep for 2 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '2s'

  automated-confirmation-approval:
    name: 'Closed Workflow for confirmation'
    environment: 'bot_completion'
    runs-on: ubuntu-20.04
    needs: 
      - transiton-to-completion
    steps:
      - run: echo "approved"

  end:
    name: 'End workflow'
    runs-on: ubuntu-20.04
    needs: 
      - automated-confirmation-approval
    steps:
      - run: echo "approved"

  

