name: Workflow with manual approval

env:
  GH_TOKEN: ${{ github.token }}

concurrency: ci-${{ github.ref }}

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
